spring:
  application:
    name: cloud_server         # 应用名称
  cloud:
    inetutils:
      timeout-seconds: 10
  security:                   # 登录  注册中心校验
    basic:
      enabled: true         # 开启基于HTTP basic的认证
    user:
      name: Qsy
      password: 123456
server:
  port: 9090                   # 服务端口
eureka:
  server:
    enable-self-preservation: false # 关闭自我保护模式（缺省为启动，比如api提供者关闭了，但是eureka仍然会保留）
    eviction-interval-timer-in-ms: 10000 # 清理间隔（毫秒，默认 60秒），将有问题的api提供者或app消费者剔除掉
  instance:
    hostname: localhost        # 设置主机名
    prefer-ip-address: true    # 注册中心可视化中显示IP地址
  client:
    registerWithEureka: false  #是否向 Eureka 注册服务。该应用为服务注册中心，不需要自注册，设置为 false
    fetchRegistry: false       #是否检索服务。该应用为服务注册中心，职责为注册和发现服务，无需检索服务，设置为 false
    serviceUrl:
                               #注册中心地址，如果多个注册中心用逗号拼接
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/